### ISSUE TITLE
User can search products with a search term

### ISSUE THREAD

**Issue by junoulee** [junoulee/final-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can search products with a search term.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will have access to a variety of product options through a simple search.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/117887912/220174192-c4c39322-675e-4f5f-b6ca-4fcc149dbe63.png)
![image](https://user-images.githubusercontent.com/117887912/220174273-950466a1-2b15-420a-98b3-9c558ed8f322.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Create proper database tables on `dbdesigner`
- [x] Update `schema.sql` to construct product/order/user tables
- [x] Update `data.sql` to populate data into database
- [x] Run `npm run db:import` to import data

### ☁️ Server Tasks

- [x] Update `server/index.js` to retrieve data from database using `app.get`
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a `navbar` component
- [x] Design `home` page with a carousel as well as images.
- [x] Define functions to `fetch` data from database when user enters a keyword in the search bar.
  - [x] Confirm that both enter as well as clicking on the search button send `get` requests.
  - [x] Confirm that blank entries do not get submitted.
  - [x] Design a drop-down menu for the search bar that'll display search suggestions.
  - [x] Define a function that'll filter through all products to display product suggestions based on users' keystrokes.
  - [x] Add an `onClick` event handler to each suggestion in order to make a `fetch` request for each suggestion.
  - [x] Once user submits a search term, close the suggestions dropdown.
  - [x] Incorporate `X` button on the search bar to close suggestions dropdown at any point
  - [x] Configure displays on the `home` page to be clickable links that also send `fetch` requests to the database.

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
