### ISSUE TITLE
User can view a list of search results

### ISSUE THREAD

**Issue by junoulee** [junoulee/final-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view a list of search results.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can browse through the available products they have searched.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/117887912/220174713-48f84bb0-f56f-480b-9601-108f02784205.png)
![image](https://user-images.githubusercontent.com/117887912/220174751-0fc6007f-44ef-4a7d-852d-cea5ab2307af.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ⚡ Client Tasks

- [x] Design search results page that displays user's search results.
  - [x] Define function(s) for view swapping from `search` page to `search results` page. 
  - [x] Allow user to return to `home` page by clicking on logo.
- [x] Design search result cards.
- [x] Design a `footer` component.

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
