### ISSUE TITLE
User can view product details

### ISSUE THREAD

**Issue by junoulee** [junoulee/final-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view product details.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can view specific product details, shipping information, and be given an option to add to cart or add to wish list. 
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/117887912/220175589-fcfd8571-6c06-43a2-adcc-f75f950d4e02.png)
![image](https://user-images.githubusercontent.com/117887912/220175634-c398e434-780c-436a-a078-f3ceb7d47fa0.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` to retrieve `productId` as well as configure `react router`.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Define functions that display product details if a search result card is clicked in the `product-view.jsx` component.
  - [x] Set up a `fetch` request to the `productId` endpoint. 
  - [x] Route the user to a new page using `react router` to view product details.
  - [x] Design component that will display product details when rendered.
- [x] Update `index.jsx` and `app.jsx` to enable use of `react router`.

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
