### ISSUE TITLE
User can create account & log in

### ISSUE THREAD

**Issue by junoulee** [junoulee/final-project#43]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can create an account and log in.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can create an account from the create account page and log in using the account they have just created.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/117887912/227796049-2fa429dd-6b44-4e13-a3ab-29264f11b164.png)
![image](https://user-images.githubusercontent.com/117887912/227796067-7990b6dc-307e-42c0-8d84-5cfc052ee479.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `schema.sql` to add `userId`, `email`, and `hashedPassword` to the `users` table. 

### ☁️ Server Tasks

- [x] Update `server/index.js` to add a `post` request to the `/api/register/` endpoint when user creates an account.
    - [x] Use Argon2 password-hashing to hash the user's password.
    - [x] Insert user's email, hashed password, and timestamp into the `users` table.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create 2 components: `login-page.jsx` and `create-account.jsx`.
    - [ ] `login-page.jsx` should allow users to input log in credentials and direct them to `create-account` page.
    - [x] `create-account.jsx` should allow users to create log in credentials.
    - [x] In `create-account.jsx`, define a function that `post` new user information to the `/api/register` endpoint.
    - [x] Define functions that validates user input when entering an email address, password, and confirming password to make sure each input is valid.

### 🧑‍⚕️ Clean Up Tasks

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
